# Generated by Django 4.2.2 on 2023-08-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='views',
        ),
        migrations.AddField(
            model_name='tweet',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
